<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <Compile Remove="Migrations\**" />
	  <EmbeddedResource Remove="Migrations\**" />
	  <None Remove="Migrations\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Module.AI.Application\Module.AI.Application.csproj" />
		<ProjectReference Include="..\Module.AI.Endpoints\Module.AI.Endpoints.csproj" />
	</ItemGroup>

</Project>
