<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Module.Users.Application\Module.Users.Application.csproj" />
    <ProjectReference Include="..\Module.Users.Endpoints\Module.Users.Endpoints.csproj" />
  </ItemGroup>

</Project>
