services:
  web-api:
    image: ${DOCKER_REGISTRY-}usersapi
    container_name: users.api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:17
    container_name: users.database
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/users-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
