services:
  users-api:
    image: ${DOCKER_REGISTRY-}usersapi
    container_name: users.api
    build:
      context: ./src/Web.Api
      dockerfile: Dockerfile
    ports:
      - 5100:8080
      - 5101:8081
  
    