services:

  gateway-api:
    image: ${DOCKER_REGISTRY-}gatewayapi    
    container_name: gateway-api
    build:
      context: .
      dockerfile: gateway/src/Gateway.Api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
      - user-service-api
      - resume-service-api
    networks:
          - proxy-backend

  postgre-database:
    image: postgres:17        

  pgadmin:
    image: dpage/pgadmin4    
    depends_on:
      - postgre-database  
    
  user-service-api:
    image: ${DOCKER_REGISTRY-}usersapi   
    container_name: user-service-api
    build:
      context: .
      dockerfile: user-service/src/Web.Api/Dockerfile
    ports:        
        - "5100"
        - "5101"
    depends_on:
      - postgre-database
    networks:
        - proxy-backend
  
  resume-service-api:
    image: ${DOCKER_REGISTRY-}resumesapi
    container_name: resume-service-api
    build:
        context: .
        dockerfile: resume-service/src/Web.Api/Dockerfile
    ports:
        - "5200"
        - "5201"
    depends_on:
      - postgre-database
    networks:
        - proxy-backend 

  ai-service-api:
    image: ${DOCKER_REGISTRY-}aiapi
    container_name: ai-service-api
    build:
        context: .
        dockerfile: ai-service/src/Web.Api/Dockerfile
    ports:
        - "5400:5400"
        - "5401:5401"        
    networks:
        - proxy-backend 

networks:
  proxy-backend:
    name: proxybackend
    driver: bridge
